// GENERATED by scripts/build-tokens.mjs from tokens/typography.json — do not edit.

import SwiftUI

public extension TypographyToken {

    /// Cover-level title on a book or collection screen.
    static let editorialDisplay = TypographyToken(
        name: "editorial.display",
        family: .serif,
        weight: .regular,
        size: 40,
        lineHeight: 46,
        tracking: -0.4,
        textStyle: .largeTitle,
        opticalSize: 36,
        isItalic: false,
        isUppercased: false
    )

    /// Title of a work, essay, or entry.
    static let editorialTitle = TypographyToken(
        name: "editorial.title",
        family: .serif,
        weight: .regular,
        size: 32,
        lineHeight: 38,
        tracking: -0.2,
        textStyle: .title,
        opticalSize: 28,
        isItalic: false,
        isUppercased: false
    )

    /// Chapter or section heading inside reading content.
    static let editorialHeading = TypographyToken(
        name: "editorial.heading",
        family: .serif,
        weight: .medium,
        size: 24,
        lineHeight: 30,
        tracking: -0.2,
        textStyle: .title2,
        opticalSize: 22,
        isItalic: false,
        isUppercased: false
    )

    /// Sub-section heading inside reading content.
    static let editorialSubheading = TypographyToken(
        name: "editorial.subheading",
        family: .serif,
        weight: .medium,
        size: 20,
        lineHeight: 27,
        tracking: 0,
        textStyle: .title3,
        opticalSize: 18,
        isItalic: false,
        isUppercased: false
    )

    /// Reading body at the largest comfortable measure.
    static let editorialBodyLarge = TypographyToken(
        name: "editorial.bodyLarge",
        family: .serif,
        weight: .regular,
        size: 20,
        lineHeight: 32,
        tracking: 0,
        textStyle: .body,
        opticalSize: 16,
        isItalic: false,
        isUppercased: false
    )

    /// Default long-form reading body.
    static let editorialBody = TypographyToken(
        name: "editorial.body",
        family: .serif,
        weight: .regular,
        size: 18,
        lineHeight: 29,
        tracking: 0,
        textStyle: .body,
        opticalSize: 14,
        isItalic: false,
        isUppercased: false
    )

    /// Compact reading body — previews, dense excerpt lists.
    static let editorialBodySmall = TypographyToken(
        name: "editorial.bodySmall",
        family: .serif,
        weight: .regular,
        size: 16,
        lineHeight: 26,
        tracking: 0,
        textStyle: .callout,
        opticalSize: 12,
        isItalic: false,
        isUppercased: false
    )

    /// Pull quote or highlighted passage.
    static let editorialQuote = TypographyToken(
        name: "editorial.quote",
        family: .serif,
        weight: .regular,
        size: 20,
        lineHeight: 31,
        tracking: 0,
        textStyle: .body,
        opticalSize: 16,
        isItalic: true,
        isUppercased: false
    )

    /// The margin note itself — a reader's annotation next to the text.
    static let editorialNote = TypographyToken(
        name: "editorial.note",
        family: .serif,
        weight: .regular,
        size: 15,
        lineHeight: 23,
        tracking: 0,
        textStyle: .subheadline,
        opticalSize: 12,
        isItalic: true,
        isUppercased: false
    )

    /// Attribution, citation, source line under editorial content.
    static let editorialCaption = TypographyToken(
        name: "editorial.caption",
        family: .serif,
        weight: .regular,
        size: 14,
        lineHeight: 20,
        tracking: 0,
        textStyle: .footnote,
        opticalSize: 10,
        isItalic: false,
        isUppercased: false
    )

    /// Large screen title, e.g. a scrolled-to-top nav title.
    static let uiDisplay = TypographyToken(
        name: "ui.display",
        family: .sans,
        weight: .semibold,
        size: 34,
        lineHeight: 41,
        tracking: -0.6,
        textStyle: .largeTitle,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    static let uiTitle1 = TypographyToken(
        name: "ui.title1",
        family: .sans,
        weight: .semibold,
        size: 28,
        lineHeight: 34,
        tracking: -0.4,
        textStyle: .title,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    static let uiTitle2 = TypographyToken(
        name: "ui.title2",
        family: .sans,
        weight: .semibold,
        size: 22,
        lineHeight: 28,
        tracking: -0.2,
        textStyle: .title2,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    static let uiTitle3 = TypographyToken(
        name: "ui.title3",
        family: .sans,
        weight: .semibold,
        size: 20,
        lineHeight: 25,
        tracking: -0.2,
        textStyle: .title3,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    /// Row title, card title — the emphasised sibling of ui.body.
    static let uiHeadline = TypographyToken(
        name: "ui.headline",
        family: .sans,
        weight: .semibold,
        size: 17,
        lineHeight: 22,
        tracking: 0,
        textStyle: .headline,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    /// Default interface text.
    static let uiBody = TypographyToken(
        name: "ui.body",
        family: .sans,
        weight: .regular,
        size: 17,
        lineHeight: 24,
        tracking: 0,
        textStyle: .body,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    static let uiBodyEmphasis = TypographyToken(
        name: "ui.bodyEmphasis",
        family: .sans,
        weight: .medium,
        size: 17,
        lineHeight: 24,
        tracking: 0,
        textStyle: .body,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    static let uiCallout = TypographyToken(
        name: "ui.callout",
        family: .sans,
        weight: .regular,
        size: 16,
        lineHeight: 21,
        tracking: 0,
        textStyle: .callout,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    /// Secondary row text, supporting copy.
    static let uiSubhead = TypographyToken(
        name: "ui.subhead",
        family: .sans,
        weight: .regular,
        size: 15,
        lineHeight: 20,
        tracking: 0,
        textStyle: .subheadline,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    static let uiFootnote = TypographyToken(
        name: "ui.footnote",
        family: .sans,
        weight: .regular,
        size: 13,
        lineHeight: 18,
        tracking: 0,
        textStyle: .footnote,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    /// Timestamps, counts, metadata.
    static let uiCaption = TypographyToken(
        name: "ui.caption",
        family: .sans,
        weight: .regular,
        size: 12,
        lineHeight: 16,
        tracking: 0.2,
        textStyle: .caption,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    static let uiCaptionSmall = TypographyToken(
        name: "ui.captionSmall",
        family: .sans,
        weight: .medium,
        size: 11,
        lineHeight: 14,
        tracking: 0.2,
        textStyle: .caption2,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    /// All-caps section label above a group.
    static let uiOverline = TypographyToken(
        name: "ui.overline",
        family: .sans,
        weight: .semibold,
        size: 11,
        lineHeight: 14,
        tracking: 0.8,
        textStyle: .caption2,
        opticalSize: nil,
        isItalic: false,
        isUppercased: true
    )

    static let uiButton = TypographyToken(
        name: "ui.button",
        family: .sans,
        weight: .semibold,
        size: 17,
        lineHeight: 22,
        tracking: 0,
        textStyle: .body,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )

    static let uiTabLabel = TypographyToken(
        name: "ui.tabLabel",
        family: .sans,
        weight: .medium,
        size: 10,
        lineHeight: 12,
        tracking: 0.2,
        textStyle: .caption2,
        opticalSize: nil,
        isItalic: false,
        isUppercased: false
    )
}

public extension TypographyToken.Family {
    /// PostScript names of the shipped font files, by weight and slant.
    func postScriptName(weight: TypographyToken.Weight, italic: Bool) -> String {
        switch self {
        case .sans:
            switch (weight, italic) {
            case (.regular, false): return "InstrumentSans-Regular"
            case (.regular, true): return "InstrumentSans-Italic"
            case (.medium, false): return "InstrumentSans-Medium"
            case (.medium, true): return "InstrumentSans-MediumItalic"
            case (.semibold, false): return "InstrumentSans-SemiBold"
            case (.semibold, true): return "InstrumentSans-SemiBoldItalic"
            case (.bold, false): return "InstrumentSans-Bold"
            case (.bold, true): return "InstrumentSans-BoldItalic"
            }
        case .serif:
            switch (weight, italic) {
            case (.regular, false): return "Newsreader-Regular"
            case (.regular, true): return "Newsreader-Italic"
            case (.medium, false): return "Newsreader-Medium"
            case (.medium, true): return "Newsreader-MediumItalic"
            case (.semibold, false): return "Newsreader-SemiBold"
            case (.semibold, true): return "Newsreader-SemiBoldItalic"
            case (.bold, false): return "Newsreader-Bold"
            case (.bold, true): return "Newsreader-BoldItalic"
            }
        }
    }

    /// Family name as registered with the system, for diagnostics.
    var displayName: String {
        switch self {
        case .sans: return "Instrument Sans"
        case .serif: return "Newsreader"
        }
    }
}
