#!/usr/bin/env node
// Generates the platform typography files from tokens/typography.json.
// Run: node scripts/build-tokens.mjs   (no dependencies)

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(join(root, "tokens/typography.json"), "utf8"));

const ROOT_FONT_SIZE = 16;
const styles = Object.entries(tokens.scale).filter(([key]) => !key.startsWith("$"));

const round = (n, places = 4) =>
  Number.parseFloat(n.toFixed(places)).toString();

const kebab = (name) =>
  name.replace(/\./g, "-").replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

const camel = (name) => {
  const parts = name.split(".");
  return parts
    .map((part, i) => (i === 0 ? part : part[0].toUpperCase() + part.slice(1)))
    .join("");
};

const pascal = (s) => s[0].toUpperCase() + s.slice(1);

/* ------------------------------------------------------------------ web ---- */

// A style whose min and max differ interpolates linearly between the two
// viewport bounds; anything else is a fixed rem value.
function webFontSize({ min, max }) {
  const minRem = `${round(min / ROOT_FONT_SIZE)}rem`;
  if (min === max) return minRem;
  const { minViewport, maxViewport } = tokens.fluid;
  const slope = (max - min) / (maxViewport - minViewport);
  const vw = round(slope * 100);
  const intercept = round((min - slope * minViewport) / ROOT_FONT_SIZE);
  return `clamp(${minRem}, ${intercept}rem + ${vw}vw, ${round(max / ROOT_FONT_SIZE)}rem)`;
}

function buildCss() {
  const out = [];
  out.push("/* GENERATED by scripts/build-tokens.mjs from tokens/typography.json — do not edit. */");
  out.push("");
  out.push(":root {");
  out.push("  /* families */");
  for (const [key, family] of Object.entries(tokens.family)) {
    out.push(`  --font-${key}: ${family.web.stack};`);
  }
  out.push("");
  out.push("  /* weights */");
  for (const [key, weight] of Object.entries(tokens.weight)) {
    out.push(`  --font-weight-${kebab(key)}: ${weight.$value};`);
  }
  out.push("");
  out.push("  /* tracking */");
  for (const [key, value] of Object.entries(tokens.tracking)) {
    if (key.startsWith("$")) continue;
    out.push(`  --tracking-${kebab(key)}: ${round(value.web)}em;`);
  }

  for (const [name, style] of styles) {
    const prefix = `--type-${kebab(name)}`;
    out.push("");
    if (style.$description) out.push(`  /* ${name} — ${style.$description} */`);
    else out.push(`  /* ${name} */`);
    out.push(`  ${prefix}-family: var(--font-${style.family});`);
    out.push(`  ${prefix}-size: ${webFontSize(style.web)};`);
    out.push(`  ${prefix}-line-height: ${style.web.lineHeight};`);
    out.push(`  ${prefix}-weight: var(--font-weight-${kebab(style.weight)});`);
    out.push(`  ${prefix}-tracking: var(--tracking-${kebab(style.tracking)});`);
  }
  out.push("}");
  out.push("");

  for (const [name, style] of styles) {
    const prefix = `--type-${kebab(name)}`;
    out.push(`.type-${kebab(name)} {`);
    out.push(`  font-family: var(${prefix}-family);`);
    out.push(`  font-size: var(${prefix}-size);`);
    out.push(`  line-height: var(${prefix}-line-height);`);
    out.push(`  font-weight: var(${prefix}-weight);`);
    out.push(`  letter-spacing: var(${prefix}-tracking);`);
    if (style.italic) out.push("  font-style: italic;");
    if (style.uppercase) out.push("  text-transform: uppercase;");
    if (style.family === "serif") out.push("  font-optical-sizing: auto;");
    out.push("}");
    out.push("");
  }
  return out.join("\n");
}

/* ------------------------------------------------------------------ iOS ---- */

const swiftTextStyle = {
  largeTitle: ".largeTitle",
  title1: ".title",
  title2: ".title2",
  title3: ".title3",
  headline: ".headline",
  body: ".body",
  callout: ".callout",
  subheadline: ".subheadline",
  footnote: ".footnote",
  caption1: ".caption",
  caption2: ".caption2",
};

function swiftLiteral(n) {
  return Number.isInteger(n) ? `${n}` : `${n}`;
}

function buildSwift() {
  const out = [];
  out.push("// GENERATED by scripts/build-tokens.mjs from tokens/typography.json — do not edit.");
  out.push("");
  out.push("import SwiftUI");
  out.push("");
  out.push("public extension TypographyToken {");

  for (const [name, style] of styles) {
    const ts = swiftTextStyle[style.ios.textStyle];
    if (!ts) throw new Error(`Unmapped iOS text style "${style.ios.textStyle}" on ${name}`);
    out.push("");
    if (style.$description) out.push(`    /// ${style.$description}`);
    out.push(`    static let ${camel(name)} = TypographyToken(`);
    out.push(`        name: "${name}",`);
    out.push(`        family: .${style.family},`);
    out.push(`        weight: .${style.weight},`);
    out.push(`        size: ${swiftLiteral(style.ios.size)},`);
    out.push(`        lineHeight: ${swiftLiteral(style.ios.lineHeight)},`);
    out.push(`        tracking: ${swiftLiteral(tokens.tracking[style.tracking].ios)},`);
    out.push(`        textStyle: ${ts},`);
    out.push(`        opticalSize: ${style.ios.opticalSize === undefined ? "nil" : swiftLiteral(style.ios.opticalSize)},`);
    out.push(`        isItalic: ${style.italic ? "true" : "false"},`);
    out.push(`        isUppercased: ${style.uppercase ? "true" : "false"}`);
    out.push("    )");
  }
  out.push("}");
  out.push("");

  // PostScript name tables, so the runtime never hard-codes a font file name.
  out.push("public extension TypographyToken.Family {");
  out.push("    /// PostScript names of the shipped font files, by weight and slant.");
  out.push("    func postScriptName(weight: TypographyToken.Weight, italic: Bool) -> String {");
  out.push("        switch self {");
  for (const [key, family] of Object.entries(tokens.family)) {
    const ps = family.ios.postScript;
    out.push(`        case .${key}:`);
    out.push("            switch (weight, italic) {");
    for (const weightKey of Object.keys(tokens.weight)) {
      const upright = ps[weightKey];
      const italicKey = weightKey === "regular" ? "italic" : `${weightKey}Italic`;
      const slanted = ps[italicKey] ?? upright;
      out.push(`            case (.${weightKey}, false): return "${upright}"`);
      out.push(`            case (.${weightKey}, true): return "${slanted}"`);
    }
    out.push("            }");
  }
  out.push("        }");
  out.push("    }");
  out.push("");
  out.push("    /// Family name as registered with the system, for diagnostics.");
  out.push("    var displayName: String {");
  out.push("        switch self {");
  for (const [key, family] of Object.entries(tokens.family)) {
    out.push(`        case .${key}: return "${family.$value}"`);
  }
  out.push("        }");
  out.push("    }");
  out.push("}");
  out.push("");
  return out.join("\n");
}

/* --------------------------------------------------------------- specimen -- */

function buildSpecimenRows() {
  return styles.map(([name, style]) => ({
    name,
    className: `type-${kebab(name)}`,
    family: tokens.family[style.family].$value,
    weight: tokens.weight[style.weight].$value,
    ios: style.ios,
    web: style.web,
    sizeCss: webFontSize(style.web),
  }));
}

function buildSpecimen() {
  const rows = buildSpecimenRows();
  const sample = {
    "editorial.display": "The Margins",
    "editorial.title": "Notes on a Ruined Map",
    "editorial.heading": "Chapter Four",
    "editorial.subheading": "On rereading",
    "editorial.bodyLarge": "A book is a machine to think with, and the margin is where the thinking shows.",
    "editorial.body": "A book is a machine to think with, and the margin is where the thinking shows. Every underline is a small argument with the page.",
    "editorial.bodySmall": "Every underline is a small argument with the page.",
    "editorial.quote": "We read to know we are not alone.",
    "editorial.note": "Compare this with the passage on p. 212 — the same figure, inverted.",
    "editorial.caption": "C. S. Lewis, A Grief Observed, 1961",
    "ui.display": "Library",
    "ui.title1": "Reading now",
    "ui.title2": "Highlights",
    "ui.title3": "This week",
    "ui.headline": "The Rings of Saturn",
    "ui.body": "Pick up where you left off, or start something new from your shelf.",
    "ui.bodyEmphasis": "42 notes across 7 books",
    "ui.callout": "Synced a moment ago",
    "ui.subhead": "W. G. Sebald · 296 pages",
    "ui.footnote": "Imported from Kindle",
    "ui.caption": "Aug 18 · 4 min read",
    "ui.captionSmall": "Edited",
    "ui.overline": "Recently annotated",
    "ui.button": "Add a note",
    "ui.tabLabel": "Shelf",
  };

  const items = rows.map((row) => `
    <article class="specimen">
      <header class="specimen-meta">
        <span class="specimen-name">${row.name}</span>
        <span class="specimen-spec">${row.family} ${row.weight} · iOS ${row.ios.size}/${row.ios.lineHeight}pt · web ${row.web.min === row.web.max ? `${row.web.min}px` : `${row.web.min}–${row.web.max}px`}/${row.web.lineHeight}</span>
      </header>
      <p class="${row.className} specimen-sample">${sample[row.name] ?? "The quick brown fox jumps over the lazy dog"}</p>
    </article>`).join("\n");

  return `<!-- GENERATED by scripts/build-tokens.mjs — do not edit. -->
<title>Marginalia Type Specimen</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400..700;1,400..700&family=Newsreader:ital,opsz,wght@0,6..72,200..800;1,6..72,200..800&display=swap" rel="stylesheet">
<style>
${readFileSync(join(root, "platforms/web/typography.css"), "utf8")}
:root {
  --page: #fbfaf7;
  --ink: #17150f;
  --ink-soft: #6c675c;
  --rule: #e3ded2;
}
:root:not([data-theme="light"]) { color-scheme: light dark; }
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) { --page: #12110e; --ink: #f2efe8; --ink-soft: #9b958a; --rule: #2c2a24; }
}
:root[data-theme="dark"] { --page: #12110e; --ink: #f2efe8; --ink-soft: #9b958a; --rule: #2c2a24; }
* { box-sizing: border-box; }
body { margin: 0; background: var(--page); color: var(--ink); font-family: var(--font-sans); }
main { max-width: 46rem; margin: 0 auto; padding: 4rem 1.5rem 6rem; }
.page-title { margin: 0 0 0.25rem; }
.page-sub { margin: 0 0 3rem; color: var(--ink-soft); max-width: 34rem; }
.specimen { padding: 1.5rem 0; border-top: 1px solid var(--rule); }
.specimen-meta { display: flex; flex-wrap: wrap; gap: 0.75rem; align-items: baseline; margin-bottom: 0.75rem; }
.specimen-name { font-family: var(--font-sans); font-size: 0.75rem; font-weight: 600; letter-spacing: 0.04em; }
.specimen-spec { font-family: var(--font-sans); font-size: 0.6875rem; color: var(--ink-soft); }
.specimen-sample { margin: 0; max-width: 34rem; }
</style>
<main>
  <h1 class="type-editorial-display page-title">Marginalia</h1>
  <p class="type-ui-subhead page-sub">Type specimen — Instrument Sans for interface, Newsreader for reading. Sizes shown are the iOS pt values and the web range; resize the window to see the fluid styles move.</p>
${items}
</main>
`;
}

/* ------------------------------------------------------------- scale table -- */

function buildScaleTable() {
  const rows = styles.map(([name, style]) => {
    const web = style.web.min === style.web.max
      ? `${style.web.min}px`
      : `${style.web.min}\u2013${style.web.max}px`;
    const notes = [
      style.italic ? "italic" : null,
      style.uppercase ? "uppercase" : null,
      style.ios.opticalSize !== undefined ? `opsz ${style.ios.opticalSize}` : null,
    ].filter(Boolean).join(", ");
    return `| \`${name}\` | ${tokens.family[style.family].$value} | ${tokens.weight[style.weight].$value} | ${style.ios.size}/${style.ios.lineHeight} | ${web}/${style.web.lineHeight} | \`${style.ios.textStyle}\` | ${notes || "\u2014"} |`;
  });

  return [
    "<!-- GENERATED by scripts/build-tokens.mjs from tokens/typography.json \u2014 do not edit. -->",
    "",
    "# Type scale",
    "",
    `${styles.length} semantic styles. iOS values are pt at the default Dynamic Type size (Large); web values are px, shown as a range where the style is fluid between ${tokens.fluid.minViewport}px and ${tokens.fluid.maxViewport}px viewports.`,
    "",
    "| Token | Family | Weight | iOS size/line | Web size/line | Dynamic Type anchor | Notes |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

/* ------------------------------------------------------------------ main --- */

writeFileSync(join(root, "platforms/web/typography.css"), buildCss());
writeFileSync(join(root, "platforms/ios/TypographyTokens.generated.swift"), buildSwift());
writeFileSync(join(root, "docs/specimen.html"), buildSpecimen());
writeFileSync(join(root, "docs/scale.md"), buildScaleTable());

console.log(`Generated ${styles.length} styles →`);
console.log("  platforms/web/typography.css");
console.log("  platforms/ios/TypographyTokens.generated.swift");
console.log("  docs/specimen.html");
console.log("  docs/scale.md");
